source 'https://rubygems.org'
ruby '1.9.3'
gem 'rake'
gem 'cucumber'
gem 'rspec'
gem 'page-object'
gem 'watir-webdriver'
gem 'activerecord'
gem "capybara", "< 2.0.3"
gem 'sauce-connect'
gem 'sauce-cucumber'
gem 'mysql2'
gem 'i18n', '= 0.6.1'
gem 'xpath', '~>1.0.0'
gem 'test-factory'
gem "parallel_tests", :group => :development
